### ISSUE TITLE
support action: in sort_link

### ISSUE THREAD

**Issue by ynjiun** [annkissam/rummage_phoenix#65]
Is that possible to support override :index default action with action: opts as an example below?

<%= sort_link @conn, @rummage, [field: :price, struct: :my_path, action: :my_action] %>

Currently it only support struct: option but always routed to the action :index which is not desired for my_path in my application. Any existing solution already? Please advise. Thanks.

**Comment by aditya7iyengar** [comment]
#67 is coming out with support for custom url
