### ISSUE TITLE
Unable to run in Phoenix 1.3

### ISSUE THREAD

**Issue by HangingClowns** [annkissam/rummage_phoenix#68]
I'm trying to run this in a phoenix app 1.3.2 app, but it seems no matter what I do, I keep having an issue. Can I get a bit of direction, please? :)

Using master asks me to use rummage_ecto 1.2, which says I should "use ~>Elixir 1.3.4" as a warning. Then When I try to start the app, it tells me I need postgrex (which I cannot because I'm using MSSQL due to a requirement).

I managed to somehow get it working by using master branch of `rummage_ecto`, but the `sort_link` function fails because the rummage I get back from querying my DB is using string keys, instead of atom keys.

Am I doing something wrong?

**Comment by aditya7iyengar** [comment]
Hi @HangingClowns. Currenly `rummage_ecto`'s master isn't working perfectly with `rummage_phoenix`. I would try using [`rummage_ecto 1.3.0-rc.0`](https://github.com/aditya7iyengar/rummage_ecto/releases/tag/1.3.0-rc.0)

I'm in process of coming up with `2.0` for both the packages by the end of this month

**Comment by vasspilka** [comment]
How is the `2.0` release comming up? Do you need any help?

**Comment by aditya7iyengar** [comment]
Hi @vasspilka. Thanks for checking in. The release is coming up well. I am trying to figure out a way to separate controller logic (which will handle ecto) from view, and view from templates. 

Using templates will allow people to easily override rummage default views.

Let me know if you have any suggestions on how to do this better.

I'm also adding support for different css libraries (should be simple enough).

**Comment by vasspilka** [comment]
I will be implementing Rummage to a new administration platform for my company, if I run into any issues or/and suggestion I will let you know :)

**Comment by yunixon** [comment]
Any news about v2?

**Comment by aditya7iyengar** [comment]
Hey @yunixon. It's in progress. With Annkissam helping out I was able to release 2.0 candidate for `rummage_ecto` yesterday and finalize a path forward for adding support for CSS libraries. Hopefully, we will be releasing v2 next wee :crossed_fingers:

**Comment by axelson** [comment]
Another ping. Also now we need to start thinking about Phoenix 1.4 support as well (although hopefully little has to change).

**Comment by maennchen** [comment]
@aditya7iyengar Do you have an update or need any help? I'd really like to use this lib in a project we're working on.

**Comment by MeerKatDev** [comment]
@aditya7iyengar same here, I was thinking to fork it and make it compatible with Phoenix 1.4 and Elixir 1.7, but if there are few issues to solve we can speed it up here. A pressing issue is the possibility to add a data range filter,which I could manage to simulate but still it's an ugly hack.

**Comment by dhruvbhatia** [comment]
Is there a rough estimate as to when Phoenix 1.4 support is expected? Looks like a great library, but I don't believe it's compatible with 1.4.

**Comment by ashish173** [comment]
@aditya7iyengar Any updates on the release?

**Comment by cyberlion85** [comment]
Hello! Is support planned for version 1.4?

**Comment by ericsullivan** [comment]
resolved in https://github.com/annkissam/rummage_phoenix/pull/74
